### ISSUE TITLE
Training code is missing

### ISSUE THREAD

**Issue by whohy** [donghyung87/FAPM_official#3]
This is a awesome contribution.  But I could not find the training code in this repo，will the author upload it？

**Comment by IceIce1ce** [comment]
+1

**Comment by Mirage2000i** [comment]
+1

**Comment by flyingtiger111** [comment]
+1

**Comment by eastbrother87** [comment]
Due to current contractual obligations, opening the training code at this time is impossible. I apologize for the inconvenience
