### ISSUE TITLE
wrong assignment of variables

### ISSUE THREAD

**Issue by ChetanSwitchOn** [donghyung87/FAPM_official#4]
Hey in the line number 127 and 128 of test.py script, I found some issues.

embedding_f = embeddings[0].cuda() # Fine Memory Bank
embedding_c=embeddings[1].cuda() # Coarse Memory Bank

The layer2 will be the coarse layer and layer3 will be the finer layer right?

**Comment by eastbrother87** [comment]
Features of embedding_f contain local information, while features of embedding_c contain more global information. In model.py, the features from layer2 and layer3 are sequentially fed into the embeddings by hook functions.
